const actionTypes = {
    REQUEST_TOKEN : 'REQUEST_TOKEN',
    RECEIVE_TOKEN : 'RECEIVE_TOKEN',
    REQUEST_PLANETS : 'REQUEST_PLANETS',
    RECEIVE_PLANETS : 'RECEIVE_PLANETS',
    REQUEST_VEHICLES : 'REQUEST_VEHICLES',
    RECEIVE_VEHICLES : 'RECEIVE_VEHICLES',
    REQUEST_SENDARMY : 'REQUEST_SENDARMY',
    RECEIVE_SENDARMY : 'RECEIVE_SENDARMY',
    REQUEST_DATA : 'REQUEST_DATA',
    RECEIVE_DATA : 'RECEIVE_DATA',
    SELECT_PLANET : 'SELECT_PLANET',
    SELECT_VEHICLE : 'SELECT_VEHICLE',
    UPDATE_SEARCHTIME : 'UPDATE_SEARCHTIME',
    INIT_APP : 'INIT_APP',
    RESET_APP : 'RESET_APP'
}

export default actionTypes;